#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
RAKE = ENV['RAKE'] ? ENV['RAKE'] : 'rake'
${symbol_pound} Multi-package project rakefile script.
require 'rake/clean'
require 'rake/packagetask'

[CLEAN, CLOBBER, Rake::FileList::DEFAULT_IGNORE_PATTERNS].each{|a| a.clear}
CLEAN.include("**/core*", "**/*~", "**/*.o", "**/*.log", ".coverage")
CLOBBER.include("target/*", "target/.??*")

def _get_task_opts(options={})
  require 'optparse'

  o = OptionParser.new do |opts|
    opts.banner = "Usage: ${symbol_pound}{RAKE} <opts_task> [options]"
    opts.on("-a OPTS", "--args OPTS") { |args| options[:args] = args }
  end
  options[:leftovers] = o.parse(o.order(ARGV) {})
  options
end

desc "Task example with opts: ${symbol_pound}{RAKE} _opts_task -- -a '-h'"
task :_opts_task do
  options = _get_task_opts ${symbol_pound}({ args: '' })
  puts "Options were: ${symbol_pound}{options[:args]}"
end

desc "Task example with args: ${symbol_pound}{RAKE} _args_task\[arg1,arg2\]"
task :_args_task, [:arg1] do |t, args|
  puts "Args were: ${symbol_pound}{args[:arg1]} ${symbol_pound}{args.extras.join(' ')}"
end

parent, version = '${parent}', '0.1.0'
SUBDIRS = ENV['SUBDIRS'] ? ENV['SUBDIRS'].split() : 'common app'.split()

desc 'configure \[opt1,opt2\]'
task :configure, [:opt1] do |task_name, opts|
  SUBDIRS.each { |dirX| mkdir_p(dirX + '/target')
    cd(dirX) {
      sh "sh ./configure.sh ${symbol_pound}{opts[:opt1]} ${symbol_pound}{opts.extras.join(' ')}" } }
end

desc "Default target: ${symbol_pound}{RAKE} help"
task :default => [:help]

desc "Help info"
task :help do |task_name|
  SUBDIRS.each { |dirX| cd(dirX) { sh "${symbol_pound}{RAKE} ${symbol_pound}{task_name}" } }
  puts "${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound} Top-level multiproject: ${symbol_pound}{parent} ${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}"
  puts "Usage: ${symbol_pound}{RAKE} [SUBDIRS=${symbol_pound}{SUBDIRS.join(' ')}] [task]"
  sh "${symbol_pound}{RAKE} -T"
end

task :subclean do
	SUBDIRS.each { |dirX| cd(dirX) { sh "${symbol_pound}{RAKE} clean" } }
end
task :subclobber do
	SUBDIRS.each { |dirX| cd(dirX) { sh "${symbol_pound}{RAKE} clobber" } }
end
task :clean => [:subclean]
task :clobber => [:subclobber]

[['all', 'Compile target(s)'],
  ['compile', 'Compile target(s)'],
  ['testCompile', 'Compile test target(s)'],
  ['publish', 'Publish artifact(s)']
].each do |task_name, desc_txt|
  desc desc_txt
  task :"${symbol_pound}{task_name}" do
    SUBDIRS.each { |dirX| cd(dirX) { sh "${symbol_pound}{RAKE} ${symbol_pound}{task_name}" } }
  end
end

desc 'Run test(s): rake test\[topt1,topt2\]'
task :test, [:topt1] do |task_name, topts|
  SUBDIRS.each { |dirX| cd(dirX) { sh "${symbol_pound}{RAKE} ${symbol_pound}{task_name}\\[${symbol_pound}{topts[:topt1]},${symbol_pound}{topts.extras.join(',')}\\]" } }
end

${symbol_pound}----------------------------------------
file "target/pkg/${symbol_pound}{parent}-${symbol_pound}{version}" do |t|
  mkdir_p(t.name)

  ${symbol_pound}sh "zip -9 -q --exclude @exclude.lst -r --exclude '*/target/*' - . | unzip -od ${symbol_pound}{t.name} -"
  sh "tar --format=posix --dereference --exclude-from=exclude.lst -cf - . | tar -xpf - -C ${symbol_pound}{t.name}"
end

if defined? Rake::PackageTask
  Rake::PackageTask.new(parent, version) do |p|
    ${symbol_pound} task("pkg/${symbol_pound}{parent}-${symbol_pound}{version}").invoke

    ENV.fetch('FMTS', 'tar.gz,zip').split(',').each{|fmt|
      if p.respond_to? "need_${symbol_pound}{fmt.tr('.', '_')}="
        p.send("need_${symbol_pound}{fmt.tr('.', '_')}=", true)
      else
        p.need_tar_gz = true
      end
    }
    task(:package).add_description "[FMTS=${symbol_pound}{ENV.fetch('FMTS', 'tar.gz,zip')}]"
    task(:repackage).add_description "[FMTS=${symbol_pound}{ENV.fetch('FMTS', 'tar.gz,zip')}]"
  end

  task :subpackage do
	SUBDIRS.each {|dirX| cd(dirX) {sh "${symbol_pound}{RAKE} package"}}
  end
  task :subrepackage do
	SUBDIRS.each {|dirX| cd(dirX) {sh "${symbol_pound}{RAKE} repackage"}}
  end
  task :package => :subpackage
  task :repackage => :subrepackage
else
  desc "[FMTS=${symbol_pound}{ENV.fetch('FMTS', 'tar.gz,zip')}] Package project distribution"
  task :dist => ["pkg/${symbol_pound}{parent}-${symbol_pound}{version}"] do |t|
    distdir = "${symbol_pound}{parent}-${symbol_pound}{version}"

    ENV.fetch('FMTS', 'tar.gz,zip').split(',').each{|fmt|
      case fmt
      when '7z'
        rm_rf("target/${symbol_pound}{distdir}.7z") || true
        cd('target') {sh "7za a -t7z -mx=9 ${symbol_pound}{distdir}.7z ${symbol_pound}{distdir}" || true}
      when 'zip'
        rm_rf("target/${symbol_pound}{distdir}.zip") || true
        cd('target') {sh "zip -9 -q -r ${symbol_pound}{distdir}.zip ${symbol_pound}{distdir}" || true}
      else
        #tarext = `echo ${symbol_pound}{fmt} | grep -e '^tar$' -e '^tar.xz$' -e '^tar.zst$' -e '^tar.bz2$' || echo tar.gz`.chomp
        tarext = fmt.match(%r{(^tar$|^tar.xz$|^tar.zst$|^tar.bz2$)}) ? fmt : 'tar.gz'
        rm_rf("target/${symbol_pound}{distdir}.${symbol_pound}{tarext}") || true
        cd('target') {sh "tar --posix -h -caf ${symbol_pound}{distdir}.${symbol_pound}{tarext} ${symbol_pound}{distdir}" || true}
      end
    }
    rm_rf("pkg/${symbol_pound}{distdir}") || true
    SUBDIRS.each {|dirX| cd(dirX) {sh "${symbol_pound}{RAKE} ${symbol_pound}{task_name}"}}
  end
end

[['jar', 'Jar sub-package files'],
  ['javadoc', '(javadoc) Generate API documentation(s)'],
  ['scaladoc', '(scaladoc) Generate API documentation(s)'],
  ['checkstyle', '(checkstyle) Lint check(s)'],
  ['scalastyle', '(scalastyle) Lint check(s)'],
  ['cover', 'Generate code coverage(s)'],
  ['report', 'Report code coverage(s)']
].each do |task_name, desc_txt|
  desc desc_txt
  task :"${symbol_pound}{task_name}" do
    SUBDIRS.each { |dirX| cd(dirX) { sh "${symbol_pound}{RAKE} ${symbol_pound}{task_name}" } }
  end
end

[['run', 'Run main: rake run\[arg1,arg2\]'],
  ['debug', 'Debug main: rake debug\[arg1,arg2\]']
].each do |task_name, desc_txt|
  desc desc_txt
  task :"${symbol_pound}{task_name}", [:arg1] do |t, args|
    cd('app') {
      sh "${symbol_pound}{RAKE} ${symbol_pound}{task_name}\\[${symbol_pound}{args[:arg1]},${symbol_pound}{args.extras.join(',')}\\]" }
  end
end
