#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
= ${parent.substring(0,1).toUpperCase()}${parent.substring(1)}-${name.substring(0,1).toUpperCase()}${name.substring(1)}
:author: ${author}
:email: <${email}>
:revnumber: ${version}
:description: README for ${parent.substring(0,1).toUpperCase()}${parent.substring(1)}-${name.substring(0,1).toUpperCase()}${name.substring(1)}
:hardbreaks:
:linkcss:
//:stylesheet!:

////
.adoc to .html: asciidoctor -n -a toc -a toclevels=2 foo.adoc
////

${description}

== Installation
source code tarball download:
    
        ${symbol_pound} [aria2c --check-certificate=false | wget --no-check-certificate | curl -kOL]
        FETCHCMD='aria2c --check-certificate=false'
        ${symbol_dollar}FETCHCMD https://${repohost}/${repoacct}/${parent}/[get | archive]/master.zip

version control repository clone:
        
        git clone https://${repohost}/${repoacct}/${parent}.git


#{if}("sbt" == ${buildTool})
cd <path> ; sbt [-Djava.library.path=$PREFIX/lib] compile [test:run]
sbt publishLocal
#{elseif}("rake" == ${buildTool})
cd <path> ; [sh] ./configure.sh [--prefix=$PREFIX] [--help]
rake main [check]
rake publish
#{elseif}("make" == ${buildTool})
cd <path> ; [sh] ./configure.sh [--prefix=$PREFIX] [--help]
make all [check]
make publish
#{elseif}("ant" == ${buildTool})
cd <path> ; ant [-Djava.library.path=$PREFIX/lib] compile [test]
ant publish
#{elseif}("maven" == ${buildTool})
cd <path> ; mvn [-Djava.library.path=$PREFIX/lib] compile [test]
mvn install
#{else}
cd <path> ; gradle [-Djava.library.path=$PREFIX/lib] assemble [check]
gradle install
#{end}

== Usage
#{if}("yes" == ${executable})
        [env RSRC_PATH=<path>/resources] java -jar ${parent}-${name}-<version>.jar [-h]
#{else}
        // PKG_CONFIG='pkg-config --with-path=${symbol_dollar}PREFIX/lib/pkgconfig'
        // ${symbol_dollar}PKG_CONFIG --cflags --libs <ffi-lib>
        // java [-Djava.library.path=${symbol_dollar}PREFIX/lib] ...
        
        import ${package}.Library
        ...
        val (arr1, arr2) = (Array[Int](0, 1, 2), Array[Int](10, 20, 30))
        val nested_arr = Library.cartesian_prod(arr1, arr2)
#{end}

== Author/Copyright
Copyright (c) ${date.split("-")[0]} by ${author} <${email}>


== License
Licensed under the ${license} License. See LICENSE for details.

